/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DEFAULT_XKB_LAYOUT "us"

#define DEFAULT_XKB_MODEL "pc105"

#define DEFAULT_XKB_OPTIONS NULL

#define DEFAULT_XKB_RULES "evdev"

#define DEFAULT_XKB_VARIANT NULL

#define DFLT_XKB_CONFIG_EXTRA_PATH "/usr/local/etc/xkb"

#define DFLT_XKB_CONFIG_ROOT "/usr/share/X11/xkb"

#define EXIT_INVALID_USAGE 2

#define HAVE_ASPRINTF 1

#define HAVE_EACCESS 1

#define HAVE_EUIDACCESS 1

#define HAVE_ICU 0

#define HAVE_MKOSTEMP 1

#define HAVE_MMAP 1

#define HAVE_POSIX_FALLOCATE 1

#define HAVE_SECURE_GETENV 1

#define HAVE_STRNDUP 1

#define HAVE_UNISTD_H 1

#define HAVE___BUILTIN_EXPECT 1

#define LIBXKBCOMMON_TOOL_PATH "/usr/local/libexec/xkbcommon"

#define LIBXKBCOMMON_VERSION "1.7.0"

#define WIN32_LEAN_AND_MEAN 1

#define XLOCALEDIR "/usr/local/share/X11/locale"

#define _CRT_NONSTDC_NO_DEPRECATE 1

#define _CRT_NONSTDC_NO_WARNINGS 1

#define _CRT_SECURE_NO_WARNINGS 1

#define _GNU_SOURCE 1

