metadata_version = 1.5.82
metadata_supportedMIMETypes = application/zip
metadata_supportedFileExtensions = rar 7z
android_metadata_versionCodeExtra = 16
android_metadata_writeExtStore = 1
android_metadata_bluetooth = 1
android_metadata_vibrate = 1
android_metadata_installShortcut = 1
android_metadata_xperiaPlayOptimized = 1
android_metadata_legacyStorage = 1
android_metadata_appExtStorage = 1
android_metadata_adaptiveIconIsMonochrome = 1
pnd_metadata_subcategory = Emulator
pnd_metadata_website = http://www.explusalpha.com
pnd_metadata_license = GPLv3+
pnd_metadata_licenseURL = http://www.gnu.org/licenses/gpl.html
pnd_metadata_sourceCodeURL = http://www.explusalpha.com/contents/emuex