/*
 * vicedate.h - various current date values and strings that can be used in code
 *
 * Autogenerated by genvicedate_h.sh, DO NOT EDIT !!!
 *
 * Written by
 *  Marco van den Heuvel <blackystardust68@yahoo.com>
 *
 * This file is part of VICE, the Versatile Commodore Emulator.
 * See README for copyright notice.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
 *  02111-1307  USA.
 *
 */

#ifndef VICEDATE_H
#define VICEDATE_H

#define VICEDATE_DAY 24
#define VICEDATE_DAY_STR "24"

#define VICEDATE_MONTH 12
#define VICEDATE_MONTH_STR "12"
#define VICEDATE_MONTH_SHORT "Dec"
#define VICEDATE_MONTH_LONG "December"

#define VICEDATE_YEAR 2023
#define VICEDATE_YEAR_STR "2023"
#endif
