#include "neopop.h"
#include "TLCS900h_interpret_dst.h"
#include "TLCS900h_interpret_reg.h"
#include "TLCS900h_interpret_single.h"
#include "TLCS900h_interpret_src.h"
#include "TLCS900h_interpret.h"
#include "TLCS900h_registers.h"

#include "TLCS900h_interpret_dst.cc"
#include "TLCS900h_interpret_reg.cc"
#include "TLCS900h_interpret_single.cc"
#include "TLCS900h_interpret_src.cc"
#include "TLCS900h_interpret.cc"
#include "TLCS900h_registers.cc"
