name: EX Emulators

on: [push, pull_request]

jobs:
  build:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    container: cirrusci/android-sdk:30-ndk
 
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Decode debug keystore
      env:
        DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
      run: |
        if [ -z "$DEBUG_KEYSTORE" ]
        then
           echo "No debug keystore value"
        else
           echo $DEBUG_KEYSTORE > debug.keystore.base64
           base64 --decode debug.keystore.base64 > debug.keystore
           sudo cp -f debug.keystore /root/.android/.
        fi
        
    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf
        sudo apt-get install -y automake
        sudo apt-get install -y autopoint
        sudo apt-get install -y bash
        sudo apt-get install -y clang
        sudo apt-get install -y file
        sudo apt-get install -y gawk
        sudo apt-get install -y gettext
        sudo apt-get install -y git
        sudo apt-get install -y libtool
        sudo apt-get install -y libtool-bin
        sudo apt-get install -y llvm 
        sudo apt-get install -y make
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y pkg-config
        sudo apt-get install -y unzip
        sudo apt-get upgrade -y
        echo y | sdkmanager "cmake;3.18.1"
        
    - name: Download and unzip NDK
      working-directory: /opt/android-sdk-linux/ndk
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r23-linux.zip
        unzip -qq ./android-ndk-r23-linux.zip
        
    - name: Set up environment
      run: |
        mkdir imagine-sdk
        mkdir EX-Emulators
        echo "ANDROID_NDK_PATH=/opt/android-sdk-linux/ndk/android-ndk-r23" >> $GITHUB_ENV
        echo "EMUFRAMEWORK_PATH=${{ github.workspace }}/EmuFramework" >> $GITHUB_ENV
        echo "IMAGINE_PATH=${{ github.workspace }}/imagine" >> $GITHUB_ENV
        echo "IMAGINE_SDK_PATH=${{ github.workspace }}/imagine-sdk" >> $GITHUB_ENV

    - name: Patch build.gradle
      run: |
        cp -f .github/workflows/01-change-signing-to-debug.patch imagine/make/gradle/app/
        cd imagine/make/gradle/app/
        patch -p 1 -i 01-change-signing-to-debug.patch
        rm 01-change-signing-to-debug.patch
  
    - name: Patch android.mk
      run: |
        cp -f .github/workflows/02-change-bundle-to-apk.patch imagine/make/shortcut/meta-builds/
        cd imagine/make/shortcut/meta-builds
        patch -p 1 -i 02-change-bundle-to-apk.patch
        rm 02-change-bundle-to-apk.patch
        
    - name: Run script
      run: |
        cd imagine/bundle/all
        chmod +x ./makeAll-android.sh
        ./makeAll-android.sh install
      shell: bash
          
    - name: Build environment
      run: |
        make -f $IMAGINE_PATH/android-release.mk install V=1 -j2
        make -f $EMUFRAMEWORK_PATH/android-release.mk config -j2
        make -f $EMUFRAMEWORK_PATH/android-release.mk install V=1 -j2

    - name: Build 2600.emu
      run: |
        cd 2600.emu
        make -f android-release.mk V=1 -j2
        
    - name: Build C64.emu
      run: |        
        cd C64.emu
        make -f android-release.mk V=1 -j2

    - name: Build GBA.emu
      run: |        
        cd GBA.emu
        make -f android-release.mk V=1 -j2

    - name: Build GBC.emu
      run: |        
        cd GBC.emu
        make -f android-release.mk V=1 -j2

    - name: Build MD.emu
      run: |        
        cd MD.emu
        make -f android-release.mk V=1 -j2

    - name: Build MSX.emu
      run: |        
        cd MSX.emu
        make -f android-release.mk V=1 -j2

    - name: Build NEO.emu
      run: |        
        cd NEO.emu
        make -f android-release.mk V=1 -j2

    - name: Build NES.emu
      run: |        
        cd NES.emu
        make -f android-release.mk V=1 -j2

    - name: Build NGP.emu
      run: |        
        cd NGP.emu
        make -f android-release.mk V=1 -j2

    - name: Build PCE.emu
      run: |        
        cd PCE.emu
        make -f android-release.mk V=1 -j2

    - name: Build Snes9x
      run: |        
        cd Snes9x
        make -f android-release.mk V=1 -j2

    - name: Copy Artifacts
      run: |
        cp 2600.emu/target/android-release/build/outputs/apk/release/2600Emu-release.apk EX-Emulators/2600Emu-release.apk
        cp C64.emu/target/android-release/build/outputs/apk/release/C64Emu-release.apk EX-Emulators/C64Emu-release.apk
        cp GBA.emu/target/android-release/build/outputs/apk/release/GbaEmu-release.apk EX-Emulators/GbaEmu-release.apk
        cp GBC.emu/target/android-release/build/outputs/apk/release/GbcEmu-release.apk EX-Emulators/GbcEmu-release.apk
        cp MD.emu/target/android-release/build/outputs/apk/release/MdEmu-release.apk EX-Emulators/MdEmu-release.apk
        cp MSX.emu/target/android-release/build/outputs/apk/release/MsxEmu-release.apk EX-Emulators/MsxEmu-release.apk
        cp NEO.emu/target/android-release/build/outputs/apk/release/NeoEmu-release.apk EX-Emulators/NeoEmu-release-.apk
        cp NES.emu/target/android-release/build/outputs/apk/release/NesEmu-release.apk EX-Emulators/NesEmu-release.apk
        cp NGP.emu/target/android-release/build/outputs/apk/release/NgpEmu-release.apk EX-Emulators/NgpEmu-release.apk
        cp PCE.emu/target/android-release/build/outputs/apk/release/PceEmu-release.apk EX-Emulators/PceEmu-release.apk
        cp Snes9x/target/android-release/build/outputs/apk/release/Snes9xEXPlus-release.apk EX-Emulators/Snes9xEXPlus-release.apk
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: EX-Emulators
        path: EX-Emulators/

    - name: Upload 2600.emu Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: 2600emu
        path: ${{ github.workspace }}/2600.emu/target/android-release/build/outputs/apk/release/2600Emu-release.apk
    
    - name: Upload C64.emu Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: C64emu
        path: ${{ github.workspace }}/C64.emu/target/android-release/build/outputs/apk/release/C64Emu-release.apk

    - name: Upload GBA.emu Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: GBAemu
        path: ${{ github.workspace }}/GBA.emu/target/android-release/build/outputs/apk/release/GbaEmu-release.apk
        
    - name: Upload GBC.emu Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: GBCemu
        path: ${{ github.workspace }}/GBC.emu/target/android-release/build/outputs/apk/release/GbcEmu-release.apk
        
    - name: Upload MD.emu Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: MDemu
        path: ${{ github.workspace }}/MD.emu/target/android-release/build/outputs/apk/release/MdEmu-release.apk
        
    - name: Upload MSX.emu Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: MSXemu
        path: ${{ github.workspace }}/MSX.emu/target/android-release/build/outputs/apk/release/MsxEmu-release.apk
        
    - name: Upload NEO.emu Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: NEOemu
        path: ${{ github.workspace }}/NEO.emu/target/android-release/build/outputs/apk/release/NeoEmu-release.apk
        
    - name: Upload NES.emu Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: NESemu
        path: ${{ github.workspace }}/NES.emu/target/android-release/build/outputs/apk/release/NesEmu-release.apk 
        
    - name: Upload NGP.emu Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: NGPemu
        path: ${{ github.workspace }}/NGP.emu/target/android-release/build/outputs/apk/release/NgpEmu-release.apk 
        
    - name: Upload PCE.emu Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: PCEemu
        path: ${{ github.workspace }}/PCE.emu/target/android-release/build/outputs/apk/release/PceEmu-release.apk
        
    - name: Upload Snes9x Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: Snes9x
        path: ${{ github.workspace }}/Snes9x/target/android-release/build/outputs/apk/release/Snes9xEXPlus-release.apk
