name: Mark issues and pull requests as stale

on:
  schedule:
  - cron: '0 1 * * Mon,Thu,Sat'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity.'
        stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-issue-close: 3
        days-before-pr-close: 3
        operations-per-run: 60
